name: Vitamin Dee
favicon: null
layout_spectrum: 0.48231
typography_spectrum: 0.38942
title: Vitamin Dee Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff6428'
    - '#ffffff'
    - '#ff8b58'
    - '#fead88'
    - '#ffcaad'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
