name: Vitamin Dee
favicon: null
layout_spectrum: 0.28820552537217736
typography_spectrum: 0.39128061942756176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6815868099220097
  lightness: 0.6129356946330518
  saturation: 0.2653746213763952
  rhythmicContrast: 0.1965297560673207
purpose: []
